#!/usr/bin/env python3
"""Turn MUI's XEN preset into the theme's artwork table.

    python3 scripts/convert_prefs.py [output.toml]

Reads the MUI package's `Presets/XEN.prefs` -- the preset the XEN screenshots
were drawn with -- and writes the generated fragment the theme build consumes
(default: libs/hosted/aegir-trinket/resources/themes/xen-preset.toml): a
`[sprites]` table naming every standard MUI image the preset assigns, by the
`MUII_*` role its key stands for (scripts/prefs.py), and pointing at the imported
PNG (scripts/import_theme_art.py). A two-frame mark contributes both frames --
`CheckMark` and `CheckMarkSelected` -- since the preset names the image and the
image is two frames. The theme file no longer lists its own sprites; this is
where they come from.

Only the images are taken. The preset's other values -- background patterns
(`2:m1`, `0:135`), colours (six hex digits) and fonts (`Name/Size`) -- are keyed
by MUI preference-item ids, and the SDK header names only the images, so there is
no way to say what each one *is*. A number with no name is not a migration, so
they are left behind: the theme's palette, patterns and fonts stay ours.

The generated file is committed, like the converted PNGs: the MUI package itself
never is. Run this again only when the preset changes.

Host tool only; not part of any target build.
Exit status: 0 success, 1 failure.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pins
import prefs

# The XEN artwork lives under `Images/xen`; a value's `XEN/` prefix is that
# drawer, and the rest is relative to it (scripts/import_theme_art.py).
SKIN = "XEN"
THEMES = pins.ROOT / "libs" / "hosted" / "aegir-trinket" / "resources" / "themes"
DEFAULT_OUTPUT = THEMES / "xen-preset.toml"
DEFAULT_PRESET = Path.home() / "src" / "MUI" / "MUI" / "Presets" / "XEN.prefs"

# The bitmap suffixes the importer converts; `.image` values are Amiga
# programmes (the scrollbar is one), not bitmaps, so they name no PNG.
ART_SUFFIXES = (".mf0", ".mf1", ".mbr")


def art_path(value: str) -> str | None:
    """The imported PNG a preset image value names, or None if it is not XEN art.

    A value is `<class>:<drawer>/<path>`; the drawer is the skin under Images/.
    """
    text = value.split(":", 1)[1] if ":" in value else value
    drawer, _, rest = text.partition("/")
    if drawer.upper() != SKIN or not rest or not rest.lower().endswith(ART_SUFFIXES):
        return None
    return f"{rest}.png"


def frames(name: str, path: str) -> list[tuple[str, str]]:
    """A preset image and, for a two-frame mark, its selected frame.

    A MUI mark is two frames -- frame 0 the normal look, frame 1 the selected
    one (`MUIA_Selected`) -- and the importer converted both, so the selected
    frame is emitted beside the one the preset names. A `.mbr` is a single
    bitmap and has no second frame.
    """
    if path.endswith(".mf0.png"):
        return [(name, path), (f"{name}Selected", path[: -len(".mf0.png")] + ".mf1.png")]
    return [(name, path)]


def main(argv: list[str]) -> int:
    output = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUTPUT
    if not DEFAULT_PRESET.is_file():
        pins.report(False, f"the XEN preset was not found: {DEFAULT_PRESET}")
        return 1
    try:
        found = prefs.entries(DEFAULT_PRESET)
    except (prefs.PrefsError, OSError) as problem:
        pins.report(False, f"{DEFAULT_PRESET}: {problem}")
        return 1

    sprites: list[tuple[str, str]] = []
    for key, value in found:
        name = prefs.image_name(key)
        if name is None:
            continue
        path = art_path(value.rstrip(b"\x00").decode("ascii", errors="replace"))
        if path is not None:
            sprites.extend(frames(name, path))

    lines = [
        "# Generated by scripts/convert_prefs.py from MUI's Presets/XEN.prefs.",
        "# Do not edit: run the converter again instead. The XEN preset is MUI's;",
        "# this is what it assigns, so the art comes from the preset and not this",
        "# repository (specs/trinket/theming.md).",
        "",
        "# The standard MUI images the preset assigns, an `MUII_*` role to the",
        "# imported artwork (scripts/import_theme_art.py).",
        "[sprites]",
    ]
    for name, path in sprites:
        lines.append(f'{name} = "{path}"')
    lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))
    pins.report(True, f"wrote {output.relative_to(pins.ROOT)}")
    print(f"    {len(sprites)} sprites")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
