#!/usr/bin/env python3
"""Turn a file's bytes into a C++ source file: an `extern const` array.

The toolkit's font is vendored (projects/terminus-font, pinned in
manifests/aegir.xml) and embedded rather than read at runtime, because the VFS
is a service whose file syscalls are stubbed (specs/cxx.md, specs/trinket.md).

    python3 scripts/embed_binary.py <input> <output.cc> <symbol>

The generated file defines `symbol` and `symbol_size` with external linkage, so
the consumer declares them `extern const`. It is a build artifact: regenerate
it by building, and do not edit it.
"""

from __future__ import annotations

import sys
from pathlib import Path


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2

    source = Path(argv[1])
    output = Path(argv[2])
    symbol = argv[3]
    data = source.read_bytes()

    lines = [
        f"/* Generated by scripts/embed_binary.py from {source.name}. Do not edit. */",
        "",
        f"extern const unsigned char {symbol}[] = {{",
    ]
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + " ".join(f"0x{byte:02x}," for byte in chunk))
    lines.append("};")
    lines.append(f"extern const unsigned long {symbol}_size = sizeof({symbol});")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
