#!/usr/bin/env python3
"""Generate the toolkit's character-width table from the pinned Unicode data.

    python3 scripts/gen_width_tables.py <ucd-dir> <out.cc>

Reads `EastAsianWidth.txt` and `extracted/DerivedGeneralCategory.txt` from the
UCD tree `make deps` fetched (`manifests/sources.toml`) and writes the compact
C++ table `terminal_view.cc` lays a cell grid out with: 0 columns for a
combining mark or a format/control character, 2 for an East Asian wide or
fullwidth character, 1 for everything else. The output is generated, never
committed: the build runs this as a custom command, and the conformance
harness runs it too, so the layout and the data are always the same version
(specs/terminal.md).

Stdlib only, so the host needs nothing but python3.
"""

from __future__ import annotations

import sys
from pathlib import Path

MAX_CODEPOINT = 0x10FFFF

ZERO_WIDTH_CATEGORIES = {"Mn", "Me", "Cf", "Cc"}
WIDE_WIDTHS = {"W", "F"}


def data_lines(path: Path):
    """The non-comment data lines of a UCD file."""
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            yield line


def parse_range(span: str) -> tuple[int, int]:
    first, _, last = span.partition("..")
    start = int(first, 16)
    end = int(last, 16) if last else start
    return start, end


def width_table(ucd: Path) -> bytearray:
    """One width byte per code point: 0, 1 or 2 columns."""
    widths = bytearray([1]) * (MAX_CODEPOINT + 1)

    for line in data_lines(ucd / "extracted" / "DerivedGeneralCategory.txt"):
        fields = [field.strip() for field in line.split(";")]
        if len(fields) < 2 or fields[1] not in ZERO_WIDTH_CATEGORIES:
            continue
        start, end = parse_range(fields[0])
        for cp in range(start, end + 1):
            widths[cp] = 0

    for line in data_lines(ucd / "EastAsianWidth.txt"):
        fields = [field.strip() for field in line.split(";")]
        if len(fields) < 2 or fields[1] not in WIDE_WIDTHS:
            continue
        start, end = parse_range(fields[0])
        for cp in range(start, end + 1):
            widths[cp] = 2

    return widths


def run_lengths(widths: bytearray) -> list[tuple[int, int, int]]:
    """Collapse the per-code-point array into (first, last, width) ranges."""
    ranges: list[tuple[int, int, int]] = []
    start = 0
    for cp in range(1, len(widths) + 1):
        if cp == len(widths) or widths[cp] != widths[start]:
            ranges.append((start, cp - 1, widths[start]))
            start = cp
    return ranges


def emit(ucd: Path, out: Path) -> None:
    ranges = run_lengths(width_table(ucd))

    lines: list[str] = []
    lines.append("/* Generated by scripts/gen_width_tables.py -- do not edit.")
    lines.append(" * Source: Unicode Character Database 16.0.0, pinned in")
    lines.append(" * manifests/sources.toml (specs/terminal.md).")
    lines.append(" */")
    lines.append("")
    lines.append('#include "width_tables.h"')
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace aegir::trinket::detail {")
    lines.append("namespace {")
    lines.append("")
    lines.append("struct WidthRange { char32_t first; char32_t last; uint8_t width; };")
    lines.append("")
    lines.append("constexpr WidthRange kWidthRanges[] = {")
    for first, last, width in ranges:
        lines.append(f"    {{0x{first:X}, 0x{last:X}, {width}}},")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace")
    lines.append("")
    lines.append("int char_width(char32_t c)")
    lines.append("{")
    lines.append("    std::size_t lo = 0;")
    lines.append("    std::size_t hi = sizeof(kWidthRanges) / sizeof(kWidthRanges[0]);")
    lines.append("    while (lo < hi) {")
    lines.append("        std::size_t const mid = (lo + hi) / 2;")
    lines.append("        if (c < kWidthRanges[mid].first) {")
    lines.append("            hi = mid;")
    lines.append("        } else if (c > kWidthRanges[mid].last) {")
    lines.append("            lo = mid + 1;")
    lines.append("        } else {")
    lines.append("            return kWidthRanges[mid].width;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return 1;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace aegir::trinket::detail")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"INFO  width tables: {len(ranges)} ranges", flush=True)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__.strip())
        return 2
    emit(Path(argv[0]), Path(argv[1]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
