#!/usr/bin/env python3
"""Generate the theme's C++ tables from resources/themes/xen.toml.

    python3 scripts/gen_theme.py <output.cc>

The theme file is the source of the look (specs/trinket/theming.md); this turns
each gadget's list of primitive steps into the `Step` tables theme_data.h
declares, so the toolkit interprets data instead of compiling the look in. Run
by the build and by scripts/check_theme.py; not part of any target build itself.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

import pins

THEME = pins.ROOT / "libs" / "hosted" / "aegir-trinket" / "resources" / "themes" / "xen.toml"

BEVEL = {"raised": 0, "sunken": 1}
MARK = {"up": 0, "down": 1, "left": 2, "right": 3}


def rgb(text: str) -> int:
    text = text.lstrip("#")
    if len(text) != 6:
        raise SystemExit(f"a colour must be #rrggbb, got {text!r}")
    return int(text, 16)


def parse_step(step: dict) -> tuple:
    """A step table -> a Step's fields (op, kind, inset, num, den, color, color2)."""
    inset = int(step.get("inset", 0))
    if "fill" in step:
        return ("FILL", 0, inset, 0, 1, rgb(step["fill"]), 0)
    if "bevel" in step:
        return ("BEVEL", BEVEL[step["bevel"]], inset, 0, 1, 0, 0)
    if "outline" in step:
        return ("OUTLINE", 0, inset, 0, 1, rgb(step["outline"]), 0)
    if "dither" in step:
        fg, bg = step["dither"]
        return ("DITHER", 0, inset, 0, 1, rgb(fg), rgb(bg))
    if "mark" in step:
        num, den = step.get("size", [1, 4])
        return ("MARK", MARK[step["mark"]], inset, num, den,
                rgb(step.get("light", "#ffffff")), rgb(step.get("dark", "#000000")))
    raise SystemExit(f"unknown step: {step}")


def emit(name: str, recipe: dict) -> tuple[str, str]:
    """Return (the static step array, the Recipe initializer)."""
    steps = recipe["steps"]
    lines = [f"static const Step {name}[] = {{"]
    for step in steps:
        op, kind, inset, num, den, color, color2 = parse_step(step)
        lines.append(f"    {{Prim::{op}, {kind}, {inset}, {num}, {den}, "
                     f"0x{color:06x}, 0x{color2:06x}}},")
    lines.append("};")
    return "\n".join(lines), f"{{{name}, {len(steps)}}}"


def emit_array(var: str, recipes: list[dict]) -> str:
    blocks = []
    items = []
    for i, recipe in enumerate(recipes):
        block, item = emit(f"{var}_{i}", recipe)
        blocks.append(block)
        items.append(f"    {item},")
    return "\n".join(blocks) + f"\nconst Recipe {var}[] = {{\n" + "\n".join(items) + "\n};"


def emit_single(var: str, recipe: dict) -> str:
    block, item = emit(f"{var}_steps", recipe)
    return block + f"\nconst Recipe {var} = {item};"


def main() -> int:
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if output is None:
        print("usage: gen_theme.py <output.cc>", file=sys.stderr)
        return 2
    theme = tomllib.loads(THEME.read_text())
    g = theme["gadgets"]

    parts = [
        "/* Generated by scripts/gen_theme.py from",
        " * libs/hosted/aegir-trinket/resources/themes/xen.toml. Do not edit; the",
        " * theme file is the source (specs/trinket/theming.md). */",
        "",
        "#include <aegir/trinket/theme_data.h>",
        "",
        "namespace aegir::trinket {",
        "",
        emit_array("kRecipeButton",
                   [g["button"][n] for n in ("normal", "hovered", "pressed",
                                             "focused", "disabled")]),
        "",
        emit_array("kRecipeTextbox", [g["textbox"]["normal"], g["textbox"]["focused"]]),
        "",
        emit_single("kRecipeTextboxReadonly", g["textbox"]["readonly"]),
        "",
        emit_array("kRecipePanel",
                   [g["panel"][n] for n in ("flat", "raised", "sunken", "frame",
                                            "group_box")]),
        "",
        emit_single("kRecipeScrollbarFrame", g["scrollbar"]["frame"]),
        "",
        emit_single("kRecipeScrollbarTrough", g["scrollbar"]["trough"]),
        "",
        emit_single("kRecipeScrollbarThumb", g["scrollbar"]["thumb"]),
        "",
        emit_single("kRecipeScrollbarDecrement", g["scrollbar"]["decrement"]),
        "",
        emit_single("kRecipeScrollbarIncrement", g["scrollbar"]["increment"]),
        "",
        "}  // namespace aegir::trinket",
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
