/*
 * Trinket Font implementation.
 */

#include <aegir/trinket/font.h>
#include <aegir/trinket/unicode.h>

#include "bdf_text.h"

#include <algorithm>
#include <cstring>
#include <vector>

/* The embedded Terminus 12 BDF, generated by scripts/embed_binary.py from the
 * pinned projects/terminus-font/ter-u12n.bdf (specs/trinket.md). */
extern const unsigned char terminus_12_bdf[];
extern const unsigned long terminus_12_bdf_size;

namespace aegir::trinket {

namespace {

using detail::next_int;
using detail::starts_with;

/* One glyph as parsed, before the atlas is laid out. */
struct ParsedGlyph {
    uint32_t encoding = 0;
    Glyph glyph;
    std::vector<uint8_t> bits;  // width * height, 0 or 255
};

}  // namespace

const Glyph* Font::find_glyph(uint32_t codepoint) const {
    const Glyph* g = glyph(codepoint);
    if (g && g->valid) return g;
    for (Font* fb : fallbacks_) {
        g = fb->glyph(codepoint);
        if (g && g->valid) return g;
    }
    return nullptr;
}

Size Font::measure(std::u32string_view text) const {
    int width = 0;
    for (char32_t cp : text) {
        const Glyph* g = find_glyph(cp);
        if (g) width += g->advance;
    }
    return {width, height()};
}

Size Font::measure(std::string_view utf8) const {
    return measure(utf8_to_utf32(utf8));
}

std::vector<PositionedGlyph> Font::shape(std::u32string_view text,
                                          BidiDirection dir) const {
    static_cast<void>(dir);  // shaping direction is the BiDi arc's
    std::vector<PositionedGlyph> result;
    int x = 0;
    for (char32_t cp : text) {
        const Glyph* g = find_glyph(cp);
        if (g && g->valid) {
            PositionedGlyph pg;
            pg.glyph = *g;
            pg.x = x + g->bearing_x;
            pg.y = -g->bearing_y;
            result.push_back(pg);
            x += g->advance;
        }
    }
    return result;
}

void Font::add_fallback(std::unique_ptr<Font> font) {
    fallbacks_.push_back(font.get());
    owned_fallbacks_.push_back(std::move(font));
}

std::vector<std::string> Font::fallback_families_for_locale(const Locale& locale) {
    std::vector<std::string> families;
    std::string lang = locale.language();

    if (lang == "zh" || lang == "ja" || lang == "ko") {
        families = {"Noto Sans CJK", "Noto Sans SC", "Noto Sans TC", "Noto Sans JP", "Noto Sans KR"};
    } else if (lang == "ar" || lang == "fa" || lang == "ur") {
        families = {"Noto Sans Arabic", "Noto Naskh Arabic"};
    } else if (lang == "he") {
        families = {"Noto Sans Hebrew"};
    } else if (lang == "hi" || lang == "mr" || lang == "ne") {
        families = {"Noto Sans Devanagari"};
    } else if (lang == "th") {
        families = {"Noto Sans Thai"};
    }
    families.push_back("Noto Sans");  // Universal fallback
    return families;
}

// BitmapFont implementation
BitmapFont::~BitmapFont() = default;

bool BitmapFont::load_bdf(const void* data, size_t size) {
    char const* const begin = static_cast<char const*>(data);
    char const* const end = begin + size;
    char const* cursor = begin;

    auto next_line = [&](std::string_view& line) -> bool {
        if (cursor >= end) return false;
        char const* const newline =
            static_cast<char const*>(memchr(cursor, '\n', end - cursor));
        char const* const line_end = newline != nullptr ? newline : end;
        size_t length = static_cast<size_t>(line_end - cursor);
        if (length > 0 && cursor[length - 1] == '\r') --length;
        line = std::string_view(cursor, length);
        cursor = newline != nullptr ? newline + 1 : end;
        return true;
    };

    glyph_map_.clear();
    atlas_ = Atlas{};
    ascent_ = 0;
    descent_ = 0;

    std::vector<ParsedGlyph> parsed;
    ParsedGlyph current;
    bool in_bitmap = false;
    int bitmap_row = 0;

    std::string_view line;
    while (next_line(line)) {
        if (in_bitmap) {
            if (bitmap_row < current.glyph.height) {
                for (int x = 0; x < current.glyph.width; ++x) {
                    int const byte = x / 8;
                    int const bit = 7 - (x % 8);
                    if (byte * 2 + 1 < static_cast<int>(line.size())) {
                        int const value = (hex_val(line[byte * 2]) << 4) |
                                          hex_val(line[byte * 2 + 1]);
                        if ((value & (1 << bit)) != 0) {
                            current.bits[static_cast<size_t>(bitmap_row) *
                                             current.glyph.width +
                                         x] = 255;
                        }
                    }
                }
                ++bitmap_row;
            }
            if (bitmap_row >= current.glyph.height) {
                in_bitmap = false;
            }
            continue;
        }

        if (starts_with(line, "FONT_ASCENT")) {
            std::string_view rest = line.substr(11);
            next_int(rest, ascent_);
        } else if (starts_with(line, "FONT_DESCENT")) {
            std::string_view rest = line.substr(12);
            next_int(rest, descent_);
        } else if (starts_with(line, "STARTCHAR")) {
            current = ParsedGlyph{};
        } else if (starts_with(line, "ENCODING")) {
            int encoding = 0;
            std::string_view rest = line.substr(8);
            if (next_int(rest, encoding) && encoding >= 0) {
                current.encoding = static_cast<uint32_t>(encoding);
            }
        } else if (starts_with(line, "DWIDTH")) {
            int advance = 0;
            std::string_view rest = line.substr(6);
            if (next_int(rest, advance)) {
                current.glyph.advance = advance;
            }
        } else if (starts_with(line, "BBX")) {
            int width = 0;
            int height = 0;
            int xoff = 0;
            int yoff = 0;
            std::string_view rest = line.substr(3);
            if (next_int(rest, width) && next_int(rest, height) &&
                next_int(rest, xoff) && next_int(rest, yoff)) {
                current.glyph.width = width;
                current.glyph.height = height;
                current.glyph.bearing_x = xoff;
                // BDF's y offset is from the baseline, positive up; the
                // canvas aligns a glyph by its distance above the baseline.
                current.glyph.bearing_y = yoff + height;
                current.glyph.valid = width > 0 && height > 0;
                if (current.glyph.valid) {
                    current.bits.assign(static_cast<size_t>(width) * height, 0);
                } else {
                    current.bits.clear();
                }
            }
        } else if (starts_with(line, "BITMAP")) {
            if (current.glyph.valid) {
                in_bitmap = true;
                bitmap_row = 0;
            }
        } else if (starts_with(line, "ENDCHAR")) {
            if (current.glyph.valid) {
                parsed.push_back(std::move(current));
            }
            current = ParsedGlyph{};
        }
    }

    if (parsed.empty()) return false;

    std::sort(parsed.begin(), parsed.end(),
              [](const ParsedGlyph& a, const ParsedGlyph& b) {
                  return a.encoding < b.encoding;
              });

    int max_width = 1;
    int max_height = 1;
    for (const ParsedGlyph& g : parsed) {
        max_width = std::max(max_width, g.glyph.width);
        max_height = std::max(max_height, g.glyph.height);
    }

    /* A grid atlas: one cell a glyph, 64 columns. The canvas blits a glyph
     * from its atlas_x/atlas_y cell (specs/trinket.md). */
    int const columns = 64;
    int const rows = (static_cast<int>(parsed.size()) + columns - 1) / columns;
    atlas_.width = static_cast<uint32_t>(columns * max_width);
    atlas_.height = static_cast<uint32_t>(rows * max_height);
    atlas_.pixels.assign(static_cast<size_t>(atlas_.width) * atlas_.height, 0);

    for (size_t i = 0; i < parsed.size(); ++i) {
        ParsedGlyph& g = parsed[i];
        int const col = static_cast<int>(i) % columns;
        int const row = static_cast<int>(i) / columns;
        int const origin_x = col * max_width;
        int const origin_y = row * max_height;
        g.glyph.atlas_x = origin_x;
        g.glyph.atlas_y = origin_y;
        for (int y = 0; y < g.glyph.height; ++y) {
            for (int x = 0; x < g.glyph.width; ++x) {
                if (g.bits[static_cast<size_t>(y) * g.glyph.width + x] != 0) {
                    atlas_.pixels[static_cast<size_t>(origin_y + y) *
                                      atlas_.width +
                                  origin_x + x] = 255;
                }
            }
        }
        glyph_map_.emplace(g.encoding, g.glyph);
    }

    height_ = ascent_ + descent_;
    return height_ > 0;
}

bool BitmapFont::load_pcf(const void* data, size_t size) {
    // PCF parsing would go here
    static_cast<void>(data);
    static_cast<void>(size);
    return false;
}

const Glyph* BitmapFont::glyph(uint32_t codepoint) const {
    auto const it = glyph_map_.find(codepoint);
    if (it != glyph_map_.end()) {
        return &it->second;
    }
    return nullptr;
}

bool BitmapFont::adopt_glyph(uint32_t codepoint, const Glyph& glyph, const uint8_t* bits) {
    if (glyph.width <= 0 || glyph.height <= 0) {
        /* An advance-only glyph: a space, or one whose bitmap did not fit the
         * page the rasterizer wrote into (specs/fonts.md). It still advances. */
        glyph_map_[codepoint] = glyph;
        return true;
    }
    /* A wider glyph widens every row -- a copy -- and a taller one appends
     * rows at the end, so a glyph already placed keeps its atlas_x/atlas_y.
     * The width is rounded up to a multiple of 8 so that a run of
     * one-pixel-wider glyphs does not copy the atlas for each one: a growth
     * policy, not a limit. */
    if (static_cast<uint32_t>(glyph.width) > atlas_.width) {
        uint32_t const wider = (static_cast<uint32_t>(glyph.width) + 7u) & ~7u;
        std::vector<uint8_t> grown(static_cast<size_t>(wider) * atlas_.height, 0);
        for (uint32_t y = 0; y < atlas_.height; ++y) {
            std::memcpy(&grown[static_cast<size_t>(y) * wider],
                        &atlas_.pixels[static_cast<size_t>(y) * atlas_.width],
                        atlas_.width);
        }
        atlas_.pixels = std::move(grown);
        atlas_.width = wider;
    }
    uint32_t const row = atlas_.height;
    uint32_t const needed = row + static_cast<uint32_t>(glyph.height);
    if (static_cast<size_t>(atlas_.width) * needed > atlas_.pixels.size()) {
        atlas_.pixels.resize(static_cast<size_t>(atlas_.width) * needed, 0);
    }
    atlas_.height = needed;
    for (int y = 0; y < glyph.height; ++y) {
        std::memcpy(&atlas_.pixels[(static_cast<size_t>(row) + static_cast<size_t>(y)) *
                                   atlas_.width],
                    bits + static_cast<size_t>(y) * glyph.width,
                    static_cast<size_t>(glyph.width));
    }
    Glyph placed = glyph;
    placed.atlas_x = 0;
    placed.atlas_y = static_cast<int>(row);
    glyph_map_[codepoint] = placed;
    return true;
}

// Helpers
int BitmapFont::hex_val(char c) noexcept {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    return 0;
}

std::unique_ptr<Font> Font::load_terminus(int size_pts, float scale) {
    static_cast<void>(scale);  // the bitmap is fixed-size; DPI is the scale arc's
    if (size_pts != 12) return nullptr;  // only Terminus 12 is embedded
    auto font = std::make_unique<BitmapFont>();
    if (!font->load_bdf(terminus_12_bdf, terminus_12_bdf_size)) {
        return nullptr;
    }
    return font;
}

std::unique_ptr<Font> Font::load_terminus_bold(int size_pts, float scale) {
    static_cast<void>(size_pts);
    static_cast<void>(scale);
    return nullptr;  // TODO
}

std::unique_ptr<Font> Font::create_with_fallbacks(std::string_view family,
                                                   int size_pts, float scale,
                                                   const Locale& locale) {
    static_cast<void>(family);  // family selection is a later milestone
    auto primary = load_terminus(size_pts, scale);
    if (!primary) return nullptr;

    // The fallback chain is built here when the font resources land.
    static_cast<void>(fallback_families_for_locale(locale));
    return primary;
}

} // namespace aegir::trinket
